project:
  title: "SSBD_presentaciones"
  type: website
  output-dir: "docs"

# Tables of contents -----------------
toc: false
toc-title: "Contents"
number-sections: false
number-offset: 1

## Code -----------------------------
execute: 
  echo: true

## Figures -------------------------
fig-responsive: true
logo: 00_assets/figures/logo-geoforest.png

## Filters -------------------------
lightbox: true
# filters: 
# webr:
#   packages: ["dplyr", "ggplot2", "gapminder", "forcats"]
# revealjs-plugins:
#   - drop